---
title: "SecondRoughDraftOfMCSimulation"
output: html_document
---

```{r}

# ## Install devtools if not already installed
# install.packages("devtools", repos='http://cran.us.r-project.org')
# library(devtools)
# ## Install augsynth from github
# devtools::install_github("ebenmichael/augsynth", force = T)
# library(augsynth)
## general libraries
library(dplyr)
library(tidyverse)
library(ggplot2)
library(MASS)
# reticulate library allows using python functions in R
library(reticulate)
# for parallelization
library(future)
library(furrr)

rm(list = ls())

start_time <- proc.time()

# Change the weights in model to reflect importance of common factors
rho <- 1
bias_fig_name <- 'figure/all_bias_sims_n50_rho1.pdf'
imbalance_fig_name <- 'figure/all_imbalance_sims_n50_rho1.pdf'

dir.create("figure", showWarnings = FALSE)
# store the simulation results.
dir.create("results", showWarnings = FALSE)

##### SCM function -------------------------------------

#' Solve the synth QP directly
#' @param X1 Target vector
#' @param X0 Matrix of control outcomes
#' @noRd
synth_qp <- function(X1, X0) {
  
  Pmat <- X0 %*% t(X0)
  qvec <- - t(X1) %*% t(X0)
  
  n0 <- nrow(X0)
  A <- rbind(rep(1, n0), diag(n0))
  l <- c(1, numeric(n0))
  u <- c(1, rep(1, n0))
  
  settings = osqp::osqpSettings(verbose = FALSE,
                                eps_rel = 1e-8,
                                eps_abs = 1e-8)
  sol <- osqp::solve_osqp(P = Pmat, q = qvec,
                          A = A, l = l, u = u, 
                          pars = settings)
  
  return(sol$x)
}

##### Bias 
SCMbias <- function(Y0,Y1,weights) {
  synthY0 <- (Y0%*%weights)
  gap <- Y1-synthY0 
  return(gap)
}

#### RMSE
rmse <- function(Y0,Y1,weights) {
  synthY0 <- (Y0%*%weights)
  gap <- Y1-synthY0 
  return(sqrt(mean(gap^2)))
}

generateModel <- function(t_total, k_total, trt, mu, rho, n) {
  factors <- list(
    c = seq(0.5, 1, length.out = t_total+1) # hand-code factor (common part)
  )
  factors$i <- matrix(0,nrow=t_total+1, ncol = k_total) # outcome idiosyncratic part of factor
  set.seed(1)
  for ( k in 1:k_total ) {
    series <- arima.sim(model = list(ar = 0.5), n = t_total+1) # independent AR series across outcomes
    factors$i[,k] <- 0.5 + (series - min(series)) * (1 - 0.5) / (max(series) - min(series))  # rescale so factors are in same range
    factors$i[,k] <- sort(factors$i[,k])
  }
  
  set.seed(1)
  mu$i <- matrix(0,nrow=n, ncol = k_total) # outcome idiosyncratic part of factor
  for (k in (1:k_total)) {
    mu$i[,k] <- rnorm(n)
    mu$i[,k] <- 1 + mu$i[,k] * (5 - 1) / (max(mu$i[,k] ) - min(mu$i[,k] )) # rescale so bias is in same range
  }
  cor(mu$i[,1],mu$c)
  cor(mu$i[,1],mu$i[,2])
  
  theo_w <- synth_qp(mu$c[trt], as.matrix(mu$c[-trt])); # confirm we can find the oracle weights
  SCMbias(mu$c[-trt]*factors$c[t_total+1], mu$c[trt]*factors$c[t_total+1],theo_w)
  
   
  mu$i[trt,] <- t(theo_w)%*%mu$i[-trt,] # overwrite the idiosyncratic loadings to ensure oracle weights exist
  
  theo_w <- synth_qp(c(mu$c[trt],mu$i[trt,]), as.matrix(cbind(mu$c[-trt],mu$i[-trt,]))); # confirm we can find the oracle weights
  SCMbias(mu$c[-trt]*factors$c[t_total+1] + mu$i[-trt,1]*factors$i[t_total+1,1],
          mu$c[trt]*factors$c[t_total+1] + mu$i[trt,1]*factors$i[t_total+1,1], 
          theo_w)
  
  # create the model components
  factors$i[,1] <- factors$c
  # Repeat each row of factors N times (expand to NT x K)
  factors_expanded <- factors$i[rep(1:(t_total+1), each = n), ]
  mu$i[,1] <- mu$c
  # Repeat mu T times (expand to NT x K)
  mu_expanded <- mu$i[rep(1:n, (t_total+1)), ]
  
  # Element-wise multiplication
  model <- rho * as.vector(factors$c %x% mu$c) + (1-rho) * factors_expanded * mu_expanded
}

#' Given the factors and factor loadings, simulate the data
#' @param factors Factors
#' @param mu Factor loadings
#' @param n number of units
#' @param trt treatment indicator vector
#' @param k_total number of outcomes
#' @param t_total number of pre-treatment periods
#' @param variance variance of the noise term
#' @param num_timepoints Number of training timepoints to use. Defaults to t_total.
factor_sim <- function(model,n,trt,k_total,t_total,variance, num_timepoints=NULL) {
  # importing the functions we want.
  # Morph reshapes the data, lq fits my model to it.
  # Need to figure out how to make these paths reproducible. - probably will need to replace with path to the files on own machine.
  morph <- reticulate::import_from_path("morphData", path = "/Users/jseid1/BSTA6700FinalProject/ScratchWork")
  lq    <- reticulate::import_from_path("learnQ", path = "/Users/jseid1/BSTA6700FinalProject/ScratchWork")

  # Use only first num_timepoints if specified
  if (!is.null(num_timepoints) & t_total == 40) {
    t_train <- num_timepoints
  } else {
    t_train <- t_total
  }
  
  epsilon <- matrix(rnorm((n * t_train) * k_total, sd = sqrt(variance)), ncol = k_total)
  out <- model[1:(n * t_train),] + epsilon # (NXT) x (K) matrix of outcomes
  t_trt <- rep(trt,t_train) # select the periods for the treated unit
  out_trt <- matrix(out[which(t_trt==1),],nrow = t_train,ncol =k_total)  # T x K matrix of outcomes for the treated unit
  out_control <- out[which(t_trt==0),] # ((N-1)xT) x (K) matrix of outcomes for the control units
  
  ## calculate SCM weights
  out_trt_sep <- out_trt[,1]
  out_control_sep <- matrix(out_control[,1], nrow = n-1,ncol=t_train)
  w_sep <- synth_qp(out_trt_sep, out_control_sep);
  r.svd <- svd(rbind(out_control_sep,out_trt_sep))
  largest_svd <- r.svd$d[1]^2/sum(r.svd$d^2)
  cond <-  r.svd$d[1]/r.svd$d[t_train]
 
  out_trt_cat <- matrix(out_trt, nrow = t_train*k_total, ncol = 1)
  out_control_cat <- matrix(out_control, nrow = n-1,ncol=t_train*k_total)
  w_cat <- synth_qp(out_trt_cat, out_control_cat);
  r.svd <- svd(rbind(out_control_cat,t(out_trt_cat)))
  largest_svd <- cbind(largest_svd, r.svd$d[1]^2/sum(r.svd$d^2))
  cond <- cbind(cond,  r.svd$d[1]/r.svd$d[length(r.svd$d)])
  
  out_trt_avg <- rowMeans(out_trt)
  out_control_avg <- matrix(rowMeans(out_control), nrow = n-1,ncol=t_train)
  w_avg <- synth_qp(out_trt_avg, out_control_avg);
  r.svd <- svd(rbind(out_control_avg,t(out_trt_avg)))
  largest_svd <- cbind(largest_svd, r.svd$d[1]^2/sum(r.svd$d^2))
  cond <- cbind(cond,  r.svd$d[1]/r.svd$d[t_total])
  
  ### ### ### ### adding the learnQ function here ### ### ### ###
  
  treated_data <- out_trt
  control_data <- out_control
  
  result <- morph$morph(treated_data, control_data)

  train_target_vectors <- result[[1]]
  train_covariate_matrices <- result[[2]]
  test_target_vector <- result[[3]]
  test_covariate_matrix <- result[[4]]
  
  # using same embedding dimension for each different simulation setting. 
  result <- lq$learnQ(train_target_vectors, train_covariate_matrices, 10L, 2000L, 1.0, 10.0, FALSE)
  
  Q_matrix <- result[[1]]
  w_learnQ <- result[[2]]
  
  # we use the Q_weights just as w_sep, w_cat, w_avg
  Q_weights <- Q_matrix %*% w_learnQ
    
  ## calculate bias
  model_t1 <- model[((n * t_total)+1):(n * (t_total+1)),]
  
  # just calculate the bias in the first outcome.
  oracle_bias_sep <- SCMbias(model_t1[-trt,1],model_t1[trt,1],w_sep)
  oracle_bias_cat <- SCMbias(model_t1[-trt,1],model_t1[trt,1],w_cat)
  oracle_bias_avg <- SCMbias(model_t1[-trt,1],model_t1[trt,1],w_avg)

   # Add bias calculation for Q weights here:
  oracle_bias_Q <- SCMbias(model_t1[-trt,1],model_t1[trt,1],Q_weights) # this may not be the correct dimensions.
  
    return(list("oracle_bias" = c(oracle_bias_sep, oracle_bias_cat, oracle_bias_avg,as.numeric(oracle_bias_Q)), # added bias_Q
            "out" = out,
            "out_trt" = out_trt,
            "out_control" = out_control,
            "model_t1" = model_t1,
            "w_sep" = w_sep,
            "w_cat" = w_cat,
            "w_avg" = w_avg
))
}

# factor loadings
n <- 50 # number of units, the first unit is treated

mu <- list(
  c = seq(5, 1, length.out = n) # N x 1 vector
)
mu$c[c(1, 2)] <- mu$c[c(2, 1)]; # hand-code factor loadings for n = 50 (common part)

trt <- numeric(n); trt[1] <- 1; # select the unit with the second largest loadings to be the treated unit

 # incorporate all settings into a loop
settings_list <- list(
  list(t_total=10, k_total=4, file_suffix="T_0=10,K=4"),
  list(t_total=10, k_total=10, file_suffix="T_0=10,K=10"),
  list(t_total=40, k_total=4, file_suffix="T_0=40,K=4"),
  list(t_total=40, k_total=10, file_suffix="T_0=40,K=10")
)    

all_bias_sim_long <- data.frame()
iteration_lengths <- data.frame(
  setting = character(),
  sim = integer(),
  iter_length = numeric()
)

for (setting in settings_list) {
  t_total <- setting$t_total
  k_total <- setting$k_total   
  
  # needs synth_qp,=
  model <- generateModel(t_total, k_total, trt, mu, rho, n)
  
  # simulation
  n_sim <- 1000
  
  columns_bias <- c("sep","cat","avg","Q")
  bias_sim <- data.frame(matrix(nrow = 0, ncol = length(columns_bias))) 
  colnames(bias_sim) <- columns_bias
  
  # Claude helped me write this parallelization piece
  plan(multisession, workers = 14)
  all_results <- future_map(1:n_sim, function(s) {
    # sketchy putting these inside but apparently thats the way to do it
    library(reticulate)
    library(dplyr)
    library(osqp)
    
    
    use_virtualenv("/Users/jseid1/venv311", required = TRUE)
    
    iter_start = proc.time()
    result <-factor_sim(model, n, trt, k_total, t_total, variance = 1, num_timepoints = 40)
    result$iter_time <- (proc.time() - iter_start)["elapsed"]
    return(result)
  }, .options = furrr_options(
    seed=215,
    globals = c("factor_sim","model","n","trt","k_total","t_total","synth_qp","SCMbias","rmse", "generateModel")
    )
  )

  # reassemble 
  for (s in 1:n_sim) {
    result <- all_results[[s]]
    iteration_lengths <- rbind(iteration_lengths, data.frame(
      setting = setting$file_suffix,
      sim = s,
      iter_length = result$iter_time
    ))
    bias_sim[s,] <- result$oracle_bias 
  }

  # bias info
  bias_sim_long <- bias_sim %>% 
    pivot_longer(columns_bias, names_to = "method", values_to = "bias") %>% mutate(setting = setting$file_suffix)
  all_bias_sim_long <- rbind(all_bias_sim_long, bias_sim_long)
  
  # summarize the simulation time info
  iteration_summary <- iteration_lengths %>%
    # there are four different settings
    group_by(setting) %>%
    summarize(
      mean_time = mean(iter_length),
      median_time = median(iter_length),
      sd_time = sd(iter_length),
      min_time = min(iter_length),
      max_time = max(iter_length)
    )
  
  # save the data
  saveRDS(all_bias_sim_long, file = "results/sim_bias4-17.rds")
  saveRDS(iteration_summary, file = "results/sim_time4-17.rds")
}
```


```{r}

sim_time <- readRDS("results/sim_time4-17.rds")
sim_time

```
